var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return c?c.call(a):$jscomp.arrayIterator(a)};$jscomp.arrayFromIterator=function(a){for(var c,d=[];!(c=a.next()).done;)d.push(c.value);return d};
$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};$jscomp.owns=function(a,c){return Object.prototype.hasOwnProperty.call(a,c)};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,d){a!=Array.prototype&&a!=Object.prototype&&(a[c]=d.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,c,d,e){if(c){d=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var f=a[e];f in d||(d[f]={});d=d[f]}a=a[a.length-1];e=d[a];c=c(e);c!=e&&null!=c&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:c})}};
$jscomp.polyfill("Object.values",function(a){return a?a:function(a){var c=[],e;for(e in a)$jscomp.owns(a,e)&&c.push(a[e]);return c}},"es8","es3");$jscomp.polyfill("Math.log10",function(a){return a?a:function(a){return Math.log(a)/Math.LN10}},"es6","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,c){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:c})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(d){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(d||"")+"_"+c++,d)}var c=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
$jscomp.iteratorFromArray=function(a,c){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var d=0,e={next:function(){if(d<a.length){var f=d++;return{value:c(f,a[f]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
$jscomp.checkStringArgs=function(a,c,d){if(null==a)throw new TypeError("The 'this' value for String.prototype."+d+" must not be null or undefined");if(c instanceof RegExp)throw new TypeError("First argument to String.prototype."+d+" must not be a regular expression");return a+""};
$jscomp.polyfill("String.prototype.startsWith",function(a){return a?a:function(a,d){var c=$jscomp.checkStringArgs(this,a,"startsWith");a+="";var f=c.length,h=a.length;d=Math.max(0,Math.min(d|0,c.length));for(var k=0;k<h&&d<f;)if(c[d++]!=a[k++])return!1;return k>=h}},"es6","es3");
$jscomp.polyfill("Object.fromEntries",function(a){return a?a:function(a){var c={};$jscomp.initSymbolIterator();if(!(Symbol.iterator in a))throw new TypeError(""+a+" is not iterable");a=a[Symbol.iterator].call(a);for(var e=a.next();!e.done;e=a.next()){e=e.value;if(Object(e)!==e)throw new TypeError("iterable for fromEntries should yield objects");c[e[0]]=e[1]}return c}},"es_2019","es3");
$jscomp.polyfill("Object.entries",function(a){return a?a:function(a){var c=[],e;for(e in a)$jscomp.owns(a,e)&&c.push([e,a[e]]);return c}},"es8","es3");$jscomp.polyfill("Array.prototype.flat",function(a){return a?a:function(a){a=void 0===a?1:a;for(var c=[],e=0;e<this.length;e++){var f=this[e];Array.isArray(f)&&0<a?(f=Array.prototype.flat.call(f,a-1),c.push.apply(c,f)):c.push(f)}return c}},"es9","es5");
$jscomp.polyfill("Array.from",function(a){return a?a:function(a,d,e){d=null!=d?d:function(a){return a};var c=[],h="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if("function"==typeof h){a=h.call(a);for(var k=0;!(h=a.next()).done;)c.push(d.call(e,h.value,k++))}else for(h=a.length,k=0;k<h;k++)c.push(d.call(e,a[k],k));return c}},"es6","es3");
$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(a,d,e){var c=this.length||0;0>d&&(d=Math.max(0,c+d));if(null==e||e>c)e=c;e=Number(e);0>e&&(e=Math.max(0,c+e));for(d=Number(d||0);d<e;d++)this[d]=a;return this}},"es6","es3");$jscomp.polyfill("Object.is",function(a){return a?a:function(a,d){return a===d?0!==a||1/a===1/d:a!==a&&d!==d}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,d){var c=this;c instanceof String&&(c=String(c));var f=c.length;d=d||0;for(0>d&&(d=Math.max(d+f,0));d<f;d++){var h=c[d];if(h===a||Object.is(h,a))return!0}return!1}},"es7","es3");$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,d){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,d||0)}},"es6","es3");
$jscomp.polyfill("Math.sign",function(a){return a?a:function(a){a=Number(a);return 0===a||isNaN(a)?a:0<a?1:-1}},"es6","es3");
for(var Materials={Line:{Edge:new THREE.LineBasicMaterial({color:0,linewidth:1})},Surface:{Ghost:new THREE.MeshBasicMaterial({color:0,side:THREE.DoubleSide,transparent:!0,blending:THREE.AdditiveBlending}),Highlighted:new THREE.MeshPhongMaterial({color:"#ff4444",side:THREE.DoubleSide,opacity:.8}),HighlightedWindow:new THREE.MeshPhongMaterial({color:"#ff4444",side:THREE.DoubleSide,opacity:.3}),Adiabatic:new THREE.MeshPhongMaterial({color:"#f24b91",side:THREE.DoubleSide,opacity:.8}),Roof:new THREE.MeshPhongMaterial({color:"#a82525",
side:THREE.DoubleSide,opacity:.5}),Inner:new THREE.MeshPhongMaterial({color:"#444444",side:THREE.DoubleSide,opacity:.5}),OuterWall:new THREE.MeshLambertMaterial({color:"#ffe16b",side:THREE.DoubleSide}),Window:new THREE.MeshPhongMaterial({color:"#00eaff",side:THREE.DoubleSide,opacity:.3}),Door:new THREE.MeshPhongMaterial({color:"#1747d4",side:THREE.DoubleSide,opacity:.5}),Shading:new THREE.MeshPhongMaterial({color:"#624285",side:THREE.DoubleSide,opacity:.7}),Ground:new THREE.MeshLambertMaterial({color:"#555555",
side:THREE.DoubleSide}),Disabled:new THREE.MeshPhongMaterial({color:"#bbbbbb",side:THREE.DoubleSide,opacity:.3})}},$jscomp$iter$1=$jscomp.makeIterator(Object.values(Materials)),$jscomp$key$matType=$jscomp$iter$1.next();!$jscomp$key$matType.done;$jscomp$key$matType=$jscomp$iter$1.next())for(var matType=$jscomp$key$matType.value,$jscomp$iter$0=$jscomp.makeIterator(Object.values(matType)),$jscomp$key$mat=$jscomp$iter$0.next();!$jscomp$key$mat.done;$jscomp$key$mat=$jscomp$iter$0.next()){var mat=$jscomp$key$mat.value;
1>mat.opacity&&(mat.transparent=!0)}Math.radians=function(a){return a*Math.PI/180};Math.degrees=function(a){return 180*a/Math.PI};var clamp=function(a,c,d){return Math.min(Math.max(a,c),d)},THRESHOLD=1E-5,isNearZero=function(a){return Math.abs(a)<THRESHOLD},isSimilar=function(a,c){return Math.abs(c-a)<THRESHOLD};function computeGridSize(a,c){c*=Math.pow(10,Math.floor(Math.log10(a/10)));return[Math.round(a/c),c]}
function computeGridTicksAuto(a,c){var d=[5,4,2].map(function(d){return computeGridSize(c-a,d)}),e=d.map(function(a){return Math.abs(8-a[0])});e=e.indexOf(Math.min.apply(Math,$jscomp.arrayFromIterable(e)));var f=d[e][1],h=Math.floor(a/f)*f;return[].concat($jscomp.arrayFromIterable(Array(Math.ceil((Math.ceil(c/f)*f-h)/f)).keys())).map(function(a){return a*f+h})}
function computeGridTicks(a,c){var d=[1,5,10,50].map(function(d){return computeGridSize(c-a,d)}),e=d.map(function(a){return Math.abs(8-a[0])});e=e.indexOf(Math.min.apply(Math,$jscomp.arrayFromIterable(e)));var f=d[e][1],h=Math.floor(a/f)*f;return[].concat($jscomp.arrayFromIterable(Array(Math.ceil((Math.ceil(c/f)*f-h)/f)).keys())).map(function(a){return a*f+h})}function roundValue(a){return Number(a.toFixed(3))}function roundValueVector(a){return new Vector(roundValue(a.x),roundValue(a.y))}
function stringToRgb(a){if(a.startsWith("#"))return hexToRgb(a);if(a.startsWith("rgb"))return rgbaStringToRgb(a)}function rgbToHex(a){r=parseInt(255*a.r);g=parseInt(255*a.g);b=parseInt(255*a.b);hex=(16777216+(r<<16)+(g<<8)+b).toString(16).slice(1);return"#"+hex}
function hexToRgb(a){hex=a.slice(1);hex=hex.replace(/^#?([a-f\d])([a-f\d])([a-f\d])$/i,function(a,d,e,f){return d+d+e+e+f+f});return(a=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex))?{r:parseInt(a[1],16)/255,g:parseInt(a[2],16)/255,b:parseInt(a[3],16)/255}:null}function rgbaStringToRgb(a){return(a=/rgba?\((\d+)\s*,\s*(\d+)\s*,\s*(\d+)(?:\s*,\s*((?:\d*[.])?\d))?\)/i.exec(a))?{r:parseInt(a[1]),g:parseInt(a[2]),b:parseInt(a[3]),a:a[4]?parseFloat(a[4]):1}:null}
function rgbToRgbaString(a){return"rgb"+(1>a.a?"a":"")+"("+a.r+", "+a.g+", "+a.b+(1>a.a?", "+a.a:"")+")"}function addWhiteToRgb(a,c){c=void 0===c?.5:c;h_str="string"==typeof a?a:rgbToHex(a);rgb=hexToRgb(h_str);return Object.fromEntries(Object.entries(rgb).map(function(a){var d=$jscomp.makeIterator(a);a=d.next().value;d=d.next().value;return[a,d*c+(1-c)]}))}function addWhiteToHex(a,c){return rgbToHex(addWhiteToRgb(a,void 0===c?.5:c))}
function addBlackToRgb(a,c){c=void 0===c?.5:c;h_str="string"==typeof a?a:rgbToHex(a);rgb=hexToRgb(h_str);return Object.fromEntries(Object.entries(rgb).map(function(a){var d=$jscomp.makeIterator(a);a=d.next().value;d=d.next().value;return[a,d*c]}))}function addBlackToHex(a,c){return rgbToHex(addBlackToRgb(a,void 0===c?.5:c))}
var floorToFloorTag=function(a){return 0<a?"F"+a:"BF"+-a},floorTagToFloor=function(a){return a.startsWith("BF")?-parseInt(a.slice(2)):parseInt(a.slice(1))},floorTextFromFloor=function(a){return 0<a?a+"F":"B"+-a+"F"};function triangulateVerticesFromFlatVertlist(a,c){c=void 0===c?null:c;var d=[];earcut(a.flat(),c,3).forEach(function(c){d.push(a[c])});return d}
function triangulatedSurfGeomFromVertlist(a,c){c=void 0===c?null:c;new THREE.Vector3(1,0,0);var d=new THREE.Vector3(0,0,1),e=new THREE.Vector3,f=new (Function.prototype.bind.apply(THREE.Vector3,[null].concat($jscomp.arrayFromIterable(a[0])))),h=new (Function.prototype.bind.apply(THREE.Vector3,[null].concat($jscomp.arrayFromIterable(a[1]))));h=(new THREE.Vector3).subVectors(h,f);for(var k=2;k<a.length&&!(e=new (Function.prototype.bind.apply(THREE.Vector3,[null].concat($jscomp.arrayFromIterable(a[k])))),
e=(new THREE.Vector3).subVectors(e,f),e=(new THREE.Vector3).crossVectors(e,h),e.length()>THRESHOLD);k++);f=new THREE.BufferGeometry;e.normalize();if((new THREE.Vector3).crossVectors(e,d).length()<THRESHOLD)a=new Float32Array(triangulateVerticesFromFlatVertlist(a,c).flat()),f.setAttribute("position",new THREE.BufferAttribute(a,3));else{var l=new THREE.Quaternion;l.setFromUnitVectors(e,d);var m=[];a.forEach(function(a){vec=new (Function.prototype.bind.apply(THREE.Vector3,[null].concat($jscomp.arrayFromIterable(a))));
vec.applyQuaternion(l);m.push([vec.x,vec.y,vec.z])});a=new Float32Array(triangulateVerticesFromFlatVertlist(m,c).flat());f.setAttribute("position",new THREE.BufferAttribute(a,3));l.invert();f.applyQuaternion(l)}f.computeVertexNormals();return f};var defaultEditorObjects={Points:{origin:{boundary:[new Vector(0,0),new Vector(0,0)],coord:new Vector(0,0),snappable:!0,texture:"#ffffff"}},Lines:{axisX:{boundary:[new Vector(0,0),new Vector(1,0)],coords:[new Vector(0,0),new Vector(1,0)],snappable:!1,texture:"#ff0000"},axisY:{boundary:[new Vector(0,0),new Vector(0,1)],coords:[new Vector(0,0),new Vector(0,1)],snappable:!1,texture:"#00ff00"}}},defaultSnapObjects={Points:{origin:[new Vector(0,0)]},Lines:{}},Building={name:"",workingPanelIdx:-1,get floors(){return this._undergroundFloors.concat(this._abovegroundFloors)},
get highestFloor(){return this.floors[this.floors.length-1]},get floorsToDraw(){var a=[Editor.currentFloor];if(Editor.showLowerFloor){var c=Building.getLowerFloor(Editor.currentFloor);c&&(a=[c].concat(a))}Editor.showUpperFloor&&(c=Building.getUpperFloor(Editor.currentFloor))&&(a=a.concat([c]));return a},get floorTagsToDraw(){return this.floorsToDraw.map(floorToFloorTag)},get floorHeights(){return this._undergroundFloorHeights.concat(this._abovegroundFloorHeights)},get floorZs(){return this._undergroundFloorZs.concat(this._abovegroundFloorZs)},
_abovegroundFloors:[1],_abovegroundFloorHeights:[3.5],_abovegroundFloorZs:[0],_undergroundFloors:[],_undergroundFloorHeights:[],_undergroundFloorZs:[],boundaryXY:[new Vector(0,0),new Vector(0,0)],get boundaryZ(){return new Vector(this.floorZs[0],this.floorZs[this.floorZs.length-1]+this.floorHeights[this.floorHeights.length-1])},addFloor:function(a){0<a?(hightestFloor=this._abovegroundFloors[this._abovegroundFloors.length-1],a>hightestFloor&&(newFloors=Array.from(Array(a-hightestFloor),function(a,
d){return d+hightestFloor+1}),this._abovegroundFloors=this._abovegroundFloors.concat(newFloors),this._abovegroundFloorHeights=this._abovegroundFloorHeights.concat(Array(newFloors.length).fill(3.5)),this.updateFloorZs())):(lowestFloor=this._undergroundFloors[0]||0,a<lowestFloor&&(newFloors=Array.from(Array(lowestFloor-a),function(c,d){return d+a}),this._undergroundFloors=newFloors.concat(this._undergroundFloors),this._undergroundFloorHeights=Array(newFloors.length).fill(3.5).concat(this._undergroundFloorHeights),
this.updateFloorZs()))},removeFloor:function(a){0<a?this._abovegroundFloors[this._abovegroundFloors.length-1]===a&&(this._abovegroundFloors.pop(),this._abovegroundFloorHeights.pop(),this.updateFloorZs()):this._undergroundFloors[0]===a&&(this._undergroundFloors.shift(),this._undergroundFloorHeights.shift(),this.updateFloorZs())},getLowerFloor:function(a){--a;0==a&&--a;return Building.floors.includes(a)?a:null},getUpperFloor:function(a){a+=1;0==a&&(a+=1);return Building.floors.includes(a)?a:null},changeFloorHeight:function(a,
c){0<a?(floorIdx=this._abovegroundFloors.indexOf(a),this._abovegroundFloorHeights[floorIdx]=c):(floorIdx=this._undergroundFloors.indexOf(a),this._undergroundFloorHeights[floorIdx]=c);this.updateFloorZs();updateViewerObjectsHeight(floorToFloorTag(a))},updateFloorZs:function(){this._abovegroundFloorZs=[0].concat(this._abovegroundFloorHeights.slice(0,-1).map((sum=0,function(a){return sum+=a})));this._undergroundFloorZs=this._undergroundFloorHeights.reverse().map((sum=0,function(a){return sum+=a})).map(function(a){return-a}).reverse()},
getFloorInfo:function(a){if(0<a)return floorIdx=this._abovegroundFloors.indexOf(a),[this._abovegroundFloorHeights[floorIdx],this._abovegroundFloorZs[floorIdx]];floorIdx=this._undergroundFloors.indexOf(a);return[this._undergroundFloorHeights[floorIdx],this._undergroundFloorZs[floorIdx]]},getFloorHeight:function(a){return this.getFloorInfo(a)[0]},getFloorZ:function(a){return this.getFloorInfo(a)[1]},resetBoundaryXY:function(){this.boundaryXY=[new Vector(Infinity,Infinity),new Vector(-Infinity,-Infinity)]},
updateBoundaryXY:function(a){this.boundaryXY=[Vector.min(this.boundaryXY[0],a[0]),Vector.max(this.boundaryXY[1],a[1])]},recomputeBoundaryXY:function(){this.resetBoundaryXY();for(var a=$jscomp.makeIterator(Object.entries(editorObjects)),c=a.next();!c.done;c=a.next()){c=$jscomp.makeIterator(c.value);c.next();c=c.next().value;c=$jscomp.makeIterator(Object.entries(c));for(var d=c.next();!d.done;d=c.next())d=$jscomp.makeIterator(d.value),d.next(),d=d.next().value,this.updateBoundaryXY(d.boundary)}}},objectNameToFloorMap=
{},editorObjects={},objectCount={},viewerObjects={};function checkBoundary(a,c){var d=!1;c[0].x<a[0].x?d=c[1].x<a[0].x?!1:!0:c[0].x<a[1].x&&(d=!0);var e=!1;c[0].y<a[0].y?e=c[1].y<a[0].y?!1:!0:c[0].y<a[1].y&&(e=!0);return d&e}
function checkSnap(a,c){Editor.inProximity=!1;Editor.proximityObject="";if(!a)return!1;if(Vector.distance(a,defaultEditorObjects.Points.origin.coord)<Editor.mouseSnapDistance)return Editor.inProximity=!0,Editor.proximityObject="origin",Editor.proximityCoord=defaultEditorObjects.Points.origin.coord,!0;for(var d=$jscomp.makeIterator(Building.floorTagsToDraw),e=d.next();!e.done;e=d.next()){e=$jscomp.makeIterator(Object.entries(editorObjects[e.value]));for(var f=e.next();!f.done;f=e.next()){var h=$jscomp.makeIterator(f.value);
f=h.next().value;h=h.next().value.coords;for(var k=0;k<h.length;k++){var l=h[k];if(Vector.distance(a,l)<Editor.mouseSnapDistance)return Editor.inProximity=!0,Editor.proximityObject=f,Editor.proximityCoord=l,!0}}}d=$jscomp.makeIterator(Building.floorTagsToDraw);for(e=d.next();!e.done;e=d.next())for(e=$jscomp.makeIterator(Object.entries(editorObjects[e.value])),f=e.next();!f.done;f=e.next()){h=$jscomp.makeIterator(f.value);f=h.next().value;h=h.next().value;k=$jscomp.makeIterator(h.coords);h=k.next().value;
l=k.next().value;k=l.sub(h);var m=a.sub(h),n=Vector.dot(m,k.unit);m=Vector.distance(k.unit.mul(n),m);if(Editor.angleSnap&&c&&!pointOnLine(c,h,l)){if(m<Editor.mouseSnapDistance&&(l=a.sub(c),l=Vector.fromAngleDeg(parseFloat(45*Math.round(l.angleDeg2/45))),n=c.sub(h),l=(l.y*n.x-l.x*n.y)/(k.x*l.y-k.y*l.x),0<=l&&1>=l))return Editor.inProximity=!0,Editor.proximityObject=f,Editor.proximityCoord=k.mul(l).add(h),!0}else if(0<=n&&n<=k.size&&m<Editor.mouseSnapDistance)return Editor.inProximity=!0,Editor.proximityObject=
f,Editor.proximityCoord=k.unit.mul(n).add(h),!0}return!1}function selectWall(a){for(var c=$jscomp.makeIterator(Object.entries(editorObjects[Editor.currentFloorTag])),d=c.next();!d.done;d=c.next()){var e=$jscomp.makeIterator(d.value);d=e.next().value;e=e.next().value;e=$jscomp.makeIterator(e.coords);var f=e.next().value;e=e.next().value.sub(f);f=a.sub(f);var h=Vector.dot(f,e.unit);if(0<=h&&h<=e.size&&Vector.distance(e.unit.mul(h),f)<Editor.mouseSnapDistance)return d}return""}
function addWallSegment(a){var c=a.floor,d=a.coords,e=void 0===a.name?"":a.name,f=void 0===a.snappable?!0:a.snappable;a=void 0===a.texture?"#fff":a.texture;var h=floorToFloorTag(c);if(""==e){var k=objectCount[h]||1;e="wall_"+h+"_"+k;objectCount[h]=k+1}objectNameToFloorMap[e]=c;k=[Vector.min.apply(Vector,$jscomp.arrayFromIterable(d)),Vector.max.apply(Vector,$jscomp.arrayFromIterable(d))];editorObjects[h][e]={boundary:k,coords:d,wwr:.5,snappable:f,texture:a};viewerObjects[h][e]=generateSurfaceAndFenestration(e,
d,Building.getFloorHeight(c),Building.getFloorZ(c),.5);Building.updateBoundaryXY(k);updateEditorViewport();addSurfaceObjectToViewer(viewerObjects[h][e])}
function removeWallSegment(a){var c=floorToFloorTag(objectNameToFloorMap[a]);Editor.hoveredWall==a&&(Editor.hoveredWall="");Editor.selectedWall==a&&(Editor.selectedWall="");delete objectNameToFloorMap[a];delete editorObjects[c][a];removeSurfaceObjectFromViewer(viewerObjects[c][a],hold=!0);delete viewerObjects[c][a];Building.recomputeBoundaryXY();updateEditorViewport();updateCamera()}
function updateWallSegmentWWR(a){var c=a.floor,d=a.name;a=a.wwr;var e=floorToFloorTag(c),f=editorObjects[e][d];editorObjects[e][d]={boundary:f.boundary,coords:f.coords,wwr:a,snappable:f.snappable,texture:f.texture};removeSurfaceObjectFromViewer(viewerObjects[e][d],hold=!0);viewerObjects[e][d]=generateSurfaceAndFenestration(d,f.coords,Building.getFloorHeight(c),Building.getFloorZ(c),a);addSurfaceObjectToViewer(viewerObjects[e][d]);Editor.selectedWall=Editor.selectedWall}
function surfaceObjectFromGeometry(a,c,d){a=new THREE.Mesh(a,c);a.renderOrder=0;a.layers.enable(1);a.name=d||"";return a}function edgeObjectFromVertList(a){var c=[];a.forEach(function(a){c.push(new (Function.prototype.bind.apply(THREE.Vector3,[null].concat($jscomp.arrayFromIterable(a)))))});c.push(c[0]);a=(new THREE.BufferGeometry).setFromPoints(c);return new THREE.Line(a,Materials.Line.Edge)}
function shadowObjectFromGeometry(a){a=new THREE.Mesh(a,Materials.Surface.Ghost);a.castShadow=!0;a.material.colorWrite=!1;a.renderOrder=Infinity;return a}
function generateSurfaceAndFenestration(a,c,d,e,f){var h=[[].concat($jscomp.arrayFromIterable(c[0]),[e]),[].concat($jscomp.arrayFromIterable(c[1]),[e]),[].concat($jscomp.arrayFromIterable(c[1]),[e+d]),[].concat($jscomp.arrayFromIterable(c[0]),[e+d])],k=c[1].sub(c[0]);c=[c[0].add(k.mul(1E-4)),c[0].add(k.mul(.9999))];adjwwr=1.0002*f;.9999<adjwwr&&(adjwwr=.9999);e=[[].concat($jscomp.arrayFromIterable(c[0]),[e+d*(1-adjwwr)/2]),[].concat($jscomp.arrayFromIterable(c[1]),[e+d*(1-adjwwr)/2]),[].concat($jscomp.arrayFromIterable(c[1]),
[e+d*(1-adjwwr)/2+d*adjwwr]),[].concat($jscomp.arrayFromIterable(c[0]),[e+d*(1-adjwwr)/2+d*adjwwr])];d={};0<f&&(f=triangulatedSurfGeomFromVertlist(e),d[a+"_winDefault"]={vertices:e,geometry:f,object:surfaceObjectFromGeometry(f,Materials.Surface.Window,a),edgeObject:edgeObjectFromVertList(e),construction:""});if(0<Object.keys(d).length)for(f=[],e=$jscomp.makeIterator(Object.values(d)),c=e.next();!c.done;c=e.next())c=c.value,f.push(h.length),h=h.concat(c.vertices);else f=null;f=triangulatedSurfGeomFromVertlist(h,
f);return{zone:"_zoneName",vertices:h,geometry:f,object:surfaceObjectFromGeometry(f,Materials.Surface.OuterWall,a),edgeObject:edgeObjectFromVertList(h),shadowObject:shadowObjectFromGeometry(f),construction:"",windows:d}}
function updateViewerObjectsHeight(a){var c=floorTagToFloor(a),d=Building.getFloorHeight(c);c=Building.getFloorZ(c);editorObjects[a]={};for(var e=$jscomp.makeIterator(Object.entries(editorObjects[a])),f=e.next();!f.done;f=e.next()){var h=$jscomp.makeIterator(f.value);f=h.next().value;h=h.next().value;viewerObjects[a][f]=generatewallaceAndFenestration(f,h.coords,d,c,h.wwr)}};var container=document.getElementsByClassName("dividerContainer")[0],panel1=document.getElementsByClassName("dividerPanel1")[0],panel2=document.getElementsByClassName("dividerPanel2")[0],canvases=document.querySelectorAll(".canvasWrapper canvas"),viewportSizes=[null,null],canvasSizes=[0,0],widthRatio=.6,heightRatio=.5,minWidthRatio=.3,minHeightRatio=.3,divider=document.getElementById("divider"),isResizing=!1;
function updateDivider(){window.innerWidth>widthThreshold?(container.style.flexDirection="row",panel1.style.height="100%",panel2.style.height="100%",panel1.style.width=100*widthRatio+"%",panel2.style.width=100*(1-widthRatio)+"%"):(container.style.flexDirection="column",panel1.style.width="100%",panel2.style.width="100%",panel1.style.height=100*heightRatio+"%",panel2.style.height=100*(1-heightRatio)+"%");for(var a=0;a<canvases.length;a++){var c=canvases[a].parentElement,d=c.parentElement.clientWidth,
e=c.parentElement.clientHeight,f=new Vector(d,e);d=Math.max(d,e);c.style.width=d+"px";c.style.height=d+"px";viewportSizes[a]=f;canvasSizes[a]=d}updateEditorOffset();updateViewerOffset()}window.onload=updateDivider;panel1.addEventListener("mousedown",function(a){Building.workingPanelIdx=0});panel2.addEventListener("mousedown",function(a){Building.workingPanelIdx=1});divider.addEventListener("mousedown",function(a){isResizing=!0;document.body.style.userSelect="none"});
document.addEventListener("mousemove",function(a){if(isResizing){var c=window.getComputedStyle(container).flexDirection,d=container.getBoundingClientRect(),e=d.width,f=d.height;"row"===c?(widthRatio=(a.clientX-d.left)/e,widthRatio=clamp(widthRatio,minWidthRatio,1-minWidthRatio)):(heightRatio=(a.clientY-d.top)/f,heightRatio=clamp(heightRatio,minHeightRatio,1-minHeightRatio));updateDivider()}});document.addEventListener("mouseup",function(){isResizing=!1;document.body.style.userSelect="auto"});
var test=null;var editorPanel=document.getElementById("editorPanel"),editorCanvas=editorPanel.querySelector("* canvas"),editorCtx=editorCanvas.getContext("2d"),editorInput=document.getElementById("editorInput"),editorInputField=document.getElementById("editorInputField"),editorInputSize=new Vector(editorInput.clientWidth,editorInput.clientHeight),floorSelector=document.getElementById("floorSelector");editorCanvas.width=editorResolution;editorCanvas.height=editorResolution;
var Editor={hold:!0,_zoom:10,center:new Vector(0,0),boundary:[new Vector(0,0),new Vector(0,0)],panning:!1,_state:-1,inputFieldVisibility:!1,inputLength:NaN,angleSnap:!0,viewportPos:new Vector(0,0),globalOffsetPosDiff:new Vector(0,0),mouseLeftStartPos:new Vector(0,0),mouseLeftStartCoord:new Vector(0,0),mouseLeftEndRawPos:new Vector(0,0),mouseLeftEndRawCoord:new Vector(0,0),mouseLeftEndAdjustedPos:new Vector(0,0),mouseLeftEndAdjustedCoord:new Vector(0,0),mouseLeftAdjustedVector:new Vector(0,0),mouseLeftEndFinalCoord:new Vector(0,
0),mouseLeftSnap:!1,mouseMiddleStartGlobalPos:new Vector(0,0),MOUSESNAPDISTANCENORM:.02,mouseSnapDistance:NaN,inProximity:!1,proximityObject:"",proximityCoord:new Vector(0,0),_currentFloor:NaN,currentFloorTag:"",hoveredWall:"",_selectedWall:"",selectedWallObject:null,showLowerFloor:!0,showUpperFloor:!1,get zoom(){return this._zoom},set zoom(a){this._zoom=a;this.mouseSnapDistance=this.MOUSESNAPDISTANCENORM*a},get state(){return this._state},set state(a){this._state=a;checkSnap(null);Editor.hoveredWall=
"";Editor.selectedWall="";0==a||1==a||2==a?(editorCanvas.style.cursor="crosshair",document.getElementById("_btnToggleDraw").checked=!0,document.getElementById("toolgroupDrawWall").style.visibility="visible"):(editorCanvas.style.cursor="",document.getElementById("_btnToggleDraw").checked=!1,document.getElementById("toolgroupDrawWall").style.visibility="");if(-1==a||0==a)hideEditorInputField(),document.removeEventListener("mousemove",mouseMoveEventEditing);this.hold||updateEditorViewport()},get currentFloor(){return this._currentFloor},
set currentFloor(a){this._currentFloor=a;this.currentFloorTag=floorToFloorTag(a);editorObjects[this.currentFloorTag]||(editorObjects[this.currentFloorTag]={});viewerObjects[this.currentFloorTag]||(viewerObjects[this.currentFloorTag]={});floorSelector.selectedIndex=Building.floors.length-Building.floors.indexOf(a);this.state=-1},get selectedWall(){return this._selectedWall},set selectedWall(a){if(this.selectedWallObject){this.selectedWallObject.object.material=Materials.Surface.OuterWall;for(var c=
$jscomp.makeIterator(Object.values(this.selectedWallObject.windows)),d=c.next();!d.done;d=c.next())winObject=d.value,winObject.object.material=Materials.Surface.Window}this._selectedWall=a;this.selectedWallObject=viewerObjects[this.currentFloorTag]&&viewerObjects[this.currentFloorTag][this._selectedWall]?viewerObjects[this.currentFloorTag][this._selectedWall]:null;if(""!=a)for(document.getElementById("toolgroupWallProp").querySelector("[data-property=wallName]").value=a,document.getElementById("toolgroupWallProp").style.visibility=
"visible",document.getElementById("inputWallWWR").value=editorObjects[this.currentFloorTag][a].wwr,d=viewerObjects[this.currentFloorTag][a],d.object.material=Materials.Surface.Highlighted,a=$jscomp.makeIterator(Object.values(d.windows)),d=a.next();!d.done;d=a.next())winObject=d.value,winObject.object.material=Materials.Surface.HighlightedWindow;else document.getElementById("toolgroupWallProp").style.visibility="hidden";this.hold||updateEditorViewport();updateCamera()}};
function updateEditorOffset(){Editor.globalOffsetPosDiff.x=parseInt(editorCanvas.getBoundingClientRect().x+document.documentElement.scrollLeft);Editor.globalOffsetPosDiff.y=parseInt(editorCanvas.getBoundingClientRect().y+document.documentElement.scrollTop);Editor.viewportPos.x=parseInt(editorPanel.getBoundingClientRect().x+document.documentElement.scrollLeft);Editor.viewportPos.y=parseInt(editorPanel.getBoundingClientRect().y+editorPanel.getBoundingClientRect().height+document.documentElement.scrollTop);
Editor.viewportPos=Editor.viewportPos.sub(Editor.globalOffsetPosDiff);updateEditorViewport()}editorCanvas.onload=updateEditorOffset;function coordToPx(a){return a.sub(Editor.center).div(Editor.zoom).flipY().add(.5,.5).mul(editorResolution)}function posToCoord(a){return a.div(canvasSizes[0]).sub(.5).flipY().mul(Editor.zoom).add(Editor.center)}function coordToPos(a){return a.sub(Editor.center).div(Editor.zoom).flipY().add(.5).mul(canvasSizes[0])}
function posToPx(a){a=posToCoord(a);return coordToPx(a)}function addWall(){Editor.state=0;coords=[Editor.mouseLeftStartCoord,Editor.mouseLeftEndFinalCoord];addWallSegment({floor:Editor.currentFloor,coords:coords,texture:"rgb(150,150,150)"})}function adjustMousePos(a,c){coord=posToCoord(a);startCoord=c?posToCoord(c):void 0;checkSnap(coord,startCoord)&&(coord=Editor.proximityCoord,a=coordToPos(coord));return[a,coord]}
function updateMouseLeftEndPoint(a){Editor.mouseLeftEndRawPos=a;Editor.mouseLeftEndRawCoord=posToCoord(a);adjustMouseLeftEndPoint()}
function adjustMouseLeftEndPoint(){var a=$jscomp.makeIterator(adjustMousePos(Editor.mouseLeftEndRawPos,Editor.mouseLeftStartPos));Editor.mouseLeftEndAdjustedPos=a.next().value;Editor.mouseLeftEndAdjustedCoord=a.next().value;if(Editor.angleSnap&&!Editor.inProximity){a=Editor.mouseLeftEndAdjustedCoord.sub(Editor.mouseLeftStartCoord);var c=parseFloat(45*Math.round(a.angleDeg2/45));c=Vector.fromAngleDeg(c);Editor.mouseLeftAdjustedVector=c.mul(Vector.dot(a,c));Editor.mouseLeftEndAdjustedCoord=Editor.mouseLeftStartCoord.add(Editor.mouseLeftAdjustedVector);
Editor.mouseLeftEndAdjustedPos=coordToPos(Editor.mouseLeftEndAdjustedCoord)}else Editor.mouseLeftAdjustedVector=Editor.mouseLeftEndAdjustedCoord.sub(Editor.mouseLeftStartCoord);a=Editor.mouseLeftAdjustedVector.div(Editor.mouseLeftAdjustedVector.size);isNaN(Editor.inputLength)?(editorInputField.placeholder=parseInt(1E3*Editor.mouseLeftAdjustedVector.size),Editor.mouseLeftEndFinalCoord=Editor.mouseLeftEndAdjustedCoord):(editorInputField.placeholder=parseInt(1E3*Editor.inputLength),Editor.mouseLeftEndFinalCoord=
Editor.mouseLeftStartCoord.add(a.mul(Editor.inputLength)))}function mouseMoveEventPanning(a){a=new Vector(a.pageX,a.pageY);var c=a.sub(Editor.mouseMiddleStartGlobalPos).flipY().div(canvasSizes[0]).mul(Editor.zoom);Editor.center=Editor.center.sub(c);Editor.mouseMiddleStartGlobalPos=a;updateEditorViewport()}
function mouseMoveEventEditing(a){1==Editor.state?updateMouseLeftEndPoint((new Vector(a.pageX,a.pageY)).sub(Editor.globalOffsetPosDiff)):2==Editor.state&&updateMouseLeftEndPoint((new Vector(a.pageX,a.pageY)).sub(Editor.globalOffsetPosDiff));updateEditorViewport()}
editorCanvas.onmouseup=function(a){0==Building.workingPanelIdx&&0==a.button&&(a=(new Vector(a.pageX,a.pageY)).sub(Editor.globalOffsetPosDiff),1==Editor.state?(Editor.state=2,updateMouseLeftEndPoint(Editor.mouseLeftStartPos)):2==Editor.state?addWall():-1==Editor.state&&(Editor.hoveredWall="",Editor.selectedWall=selectWall(posToCoord(a))))};
editorCanvas.addEventListener("mousedown",function(a){0==a.button?(0==Editor.state?(Editor.state=1,a=new Vector(a.offsetX,a.offsetY),a=$jscomp.makeIterator(adjustMousePos(a)),Editor.mouseLeftStartPos=a.next().value,Editor.mouseLeftStartCoord=a.next().value,document.addEventListener("mousemove",mouseMoveEventEditing)):2==Editor.state&&addWall(),updateEditorViewport()):1==a.button&&(Editor.panning=!0,Editor.mouseMiddleStartGlobalPos=new Vector(a.pageX,a.pageY),document.addEventListener("mousemove",
mouseMoveEventPanning))});editorCanvas.addEventListener("mousemove",function(a){a=(new Vector(a.pageX,a.pageY)).sub(Editor.globalOffsetPosDiff);0==Editor.state?checkSnap(posToCoord(a)):-1==Editor.state&&(Editor.hoveredWall=selectWall(posToCoord(a)));updateEditorViewport()});
editorCanvas.addEventListener("wheel",function(a){a.preventDefault();var c=1-clamp(a.wheelDeltaY/120,-1,1)/10;a=posToCoord(new Vector(a.offsetX,a.offsetY));Editor.zoom*=c;Editor.center=Editor.center.sub(a).mul(c).add(a);2==Editor.state&&updateMouseLeftEndPoint(Editor.mouseLeftEndRawPos);updateEditorViewport()});
function changeFloor(a){if("add lower"===a.value){var c=document.createElement("option"),d=1==Building.floors[0]?-1:Building.floors[0]-1;Building.addFloor(d);c.value=d;c.innerHTML=floorTextFromFloor(d);a.insertBefore(c,a.options[a.selectedIndex]);Editor.currentFloor=d}else"add upper"===a.value?(c=document.createElement("option"),d=Building.highestFloor+1,Building.addFloor(d),c.value=d,c.innerHTML=floorTextFromFloor(d),a.insertBefore(c,a.options[a.selectedIndex].nextSibling),Editor.currentFloor=d):
(a=parseInt(a.value),Editor.currentFloor=a)}function checkWWRValidity(a){var c=parseFloat(a.value);if(0>c||1<c)a.value=editorObjects[Editor.currentFloorTag][Editor.selectedWall].wwr}
function updateWWR(a,c){"Enter"===a.key?(a=parseFloat(c.value),0<=a&&1>=a?updateWallSegmentWWR({floor:Editor.currentFloor,name:Editor.selectedWall,wwr:a}):c.value=editorObjects[Editor.currentFloorTag][Editor.selectedWall].wwr,c.blur()):"Escape"===a.key&&(c.value=editorObjects[Editor.currentFloorTag][Editor.selectedWall].wwr,c.blur())}editorInputField.addEventListener("focusout",function(a){Editor.inputFieldVisibility=!1;editorInput.style.opacity=""});
function checkInputValidity(){var a=editorInputField.value;a=a.match(/[1-9]\d{0,4}/gm);null===a?(a="",Editor.inputLength=NaN):(a=a[0],Editor.inputLength=parseInt(a)/1E3);adjustMouseLeftEndPoint();editorInputField.value=a;setTimeout(function(){editorInputField.selectionStart=editorInputField.selectionEnd=1E4},0);renderEditorViewport()}function showEditorInputField(){Editor.inputFieldVisibility||(Editor.inputFieldVisibility=!0,editorInput.style.opacity=1,editorInputField.focus())}
function hideEditorInputField(){editorInputField.blur();editorInputField.value="";Editor.inputLength=NaN}function updateEditorInputFieldPos(a){editorInput.style.left=a.x+"px";editorInput.style.top=a.y+"px"}
function adjustEditorInputFieldLocation(a,c,d){d=void 0===d?0:d;var e=new Vector(canvasSizes[0]/2,canvasSizes[0]/2),f=viewportSizes[0].div(2);d=f.sub(editorInputSize.div(2).add(d));var h=c.sub(a).angleDeg2;f=[e.add(f),e.add(f.flipX()),e.sub(f),e.sub(f.flipX())];var k=[f[0].sub(a).angleDeg2,f[1].sub(a).angleDeg2,f[2].sub(a).angleDeg2,f[3].sub(a).angleDeg2];k[3]<h&&h<k[0]?(h=f[0].x-a.x,f=c.x-a.x):k[0]<h&&h<k[1]?(h=f[1].y-a.y,f=c.y-a.y):k[1]<h||h<k[2]?(h=a.x-f[2].x,f=a.x-c.x):(h=a.y-f[3].y,f=a.y-c.y);
c=h<f?c.sub(a).mul(h/f).add(a):c;h=editorInputSize.add(20);a=0<c.sub(a).size?c.sub(a):new Vector(1,0);f=a.unit.rotateDeg(90);k=a.abs.angle;2*a.size<(k<h.angle?h.x/Math.cos(k):h.y/Math.sin(k))&&(c=c.add(f.mul(h.size/2)));return c.sub(e).abs.x>=d.abs.x||c.sub(e).abs.y>=d.abs.y?new Vector(clamp(c.x,e.x-d.x,e.x+d.x),clamp(c.y,e.y-d.y,e.y+d.y)):c}
function renderEditorViewport(){editorCtx.reset();var a=computeGridTicks(Editor.boundary[0].x,Editor.boundary[1].x),c=computeGridTicks(Editor.boundary[0].y,Editor.boundary[1].y);editorCtx.lineWidth=1;editorCtx.strokeStyle="rgba(255,255,255,0.2)";for(var d=$jscomp.makeIterator(a),e=d.next();!e.done;e=d.next())e=e.value,editorCtx.beginPath(),editorCtx.moveTo.apply(editorCtx,$jscomp.arrayFromIterable(coordToPx(new Vector(e,Editor.boundary[0].y)))),editorCtx.lineTo.apply(editorCtx,$jscomp.arrayFromIterable(coordToPx(new Vector(e,
Editor.boundary[1].y)))),editorCtx.stroke();c=$jscomp.makeIterator(c);for(d=c.next();!d.done;d=c.next())d=d.value,editorCtx.beginPath(),editorCtx.moveTo.apply(editorCtx,$jscomp.arrayFromIterable(coordToPx(new Vector(Editor.boundary[0].x,d)))),editorCtx.lineTo.apply(editorCtx,$jscomp.arrayFromIterable(coordToPx(new Vector(Editor.boundary[1].x,d)))),editorCtx.stroke();a=a[1]-a[0];c=posToCoord(Editor.viewportPos).add(.01*Editor.zoom);editorCtx.font="bold 25px Roboto";editorCtx.textAlign="left";editorCtx.fillStyle=
"rgba(255,255,255,0.3)";editorCtx.fillText.apply(editorCtx,[a+"m"].concat($jscomp.arrayFromIterable(coordToPx(c))));editorCtx.setLineDash([]);a=$jscomp.makeIterator(Building.floorTagsToDraw);for(c=a.next();!c.done;c=a.next())if(c=c.value,[0,1,2].includes(Editor.state)||c===Editor.currentFloorTag)for(d=$jscomp.makeIterator(Object.entries(editorObjects[c]||{})),e=d.next();!e.done;e=d.next()){var f=$jscomp.makeIterator(e.value);e=f.next().value;f=f.next().value;var h=f.texture||"";if(checkBoundary(Editor.boundary,
f.boundary)&&e!=Editor.hoveredWall){e=f.coords;f=e.length;editorCtx.beginPath();editorCtx.moveTo.apply(editorCtx,$jscomp.arrayFromIterable(coordToPx(e[0])));for(var k=1;k<f;k++)editorCtx.lineTo.apply(editorCtx,$jscomp.arrayFromIterable(coordToPx(e[k])));editorCtx.lineCap="round";editorCtx.lineWidth=10;c===Editor.currentFloorTag?editorCtx.strokeStyle=h:(e=stringToRgb(h),e.a=.3,editorCtx.strokeStyle=rgbToRgbaString(e));editorCtx.stroke()}}editorCtx.setLineDash([]);c=$jscomp.makeIterator(Object.entries(defaultEditorObjects.Lines));
for(a=c.next();!a.done;a=c.next())if(a=$jscomp.makeIterator(a.value),a.next(),e=a.next().value,d=e.boundary,a=e.texture||"",checkBoundary(Editor.boundary,d)){e=e.coords;f=e.length;editorCtx.beginPath();editorCtx.moveTo.apply(editorCtx,$jscomp.arrayFromIterable(coordToPx(e[0])));for(d=1;d<f;d++)editorCtx.lineTo.apply(editorCtx,$jscomp.arrayFromIterable(coordToPx(e[d])));editorCtx.lineWidth=5;editorCtx.lineCap="round";editorCtx.strokeStyle=a+"aa";editorCtx.stroke()}c=$jscomp.makeIterator(Object.entries(defaultEditorObjects.Points));
for(a=c.next();!a.done;a=c.next())a=$jscomp.makeIterator(a.value),a.next(),e=a.next().value,d=e.boundary,a=e.texture||"",checkBoundary(Editor.boundary,d)&&(d=e.coord,editorCtx.beginPath(),editorCtx.arc.apply(editorCtx,[].concat($jscomp.arrayFromIterable(coordToPx(d)),[4,0,2*Math.PI])),editorCtx.closePath(),editorCtx.fillStyle=a,editorCtx.fill());-1==Editor.state||0==Editor.state||1!=Editor.state&&2!=Editor.state||(a=coordToPos(Editor.mouseLeftStartCoord),c=coordToPx(Editor.mouseLeftStartCoord),e=
coordToPos(Editor.mouseLeftEndFinalCoord),d=coordToPx(Editor.mouseLeftEndFinalCoord),2==Editor.state&&(editorCtx.lineWidth=2,editorCtx.lineCap="round",editorCtx.strokeStyle="rgba(158,227,255,0.8)",editorCtx.beginPath(),editorCtx.moveTo.apply(editorCtx,$jscomp.arrayFromIterable(c)),editorCtx.lineTo.apply(editorCtx,$jscomp.arrayFromIterable(d)),editorCtx.stroke(),Editor.mouseLeftAdjustedVector.size>Editor.inputLength&&(editorCtx.beginPath(),editorCtx.moveTo.apply(editorCtx,$jscomp.arrayFromIterable(d)),
editorCtx.lineTo.apply(editorCtx,$jscomp.arrayFromIterable(coordToPx(Editor.mouseLeftEndAdjustedCoord))),editorCtx.setLineDash([5,10]),editorCtx.stroke(),editorCtx.setLineDash([])),e=Vector.midPoint(a,e),e=adjustEditorInputFieldLocation(a,e,padding=10),showEditorInputField(),updateEditorInputFieldPos(e),editorCtx.beginPath(),editorCtx.arc.apply(editorCtx,[].concat($jscomp.arrayFromIterable(d),[8,0,2*Math.PI])),editorCtx.closePath(),editorCtx.stroke()),editorCtx.lineWidth=2,editorCtx.strokeStyle="rgba(158,227,255,0.8)",
editorCtx.beginPath(),editorCtx.arc.apply(editorCtx,[].concat($jscomp.arrayFromIterable(c),[8,0,2*Math.PI])),editorCtx.closePath(),editorCtx.stroke());0==Editor.state||1==Editor.state||2==Editor.state?Editor.inProximity&&(editorCtx.beginPath(),editorCtx.arc.apply(editorCtx,[].concat($jscomp.arrayFromIterable(coordToPx(Editor.proximityCoord)),[10,0,2*Math.PI])),editorCtx.closePath(),editorCtx.lineWidth=4,editorCtx.strokeStyle="#f44",editorCtx.stroke()):-1==Editor.state&&(Editor.selectedWall&&(a=editorObjects[Editor.currentFloorTag][Editor.selectedWall].coords,
editorCtx.lineCap="round",editorCtx.lineWidth=4,editorCtx.strokeStyle="#f44",highlightLine.apply(null,[editorCtx].concat($jscomp.arrayFromIterable(coordToPx(a[0])),$jscomp.arrayFromIterable(coordToPx(a[1])),[12])),editorCtx.stroke()),""!=Editor.hoveredWall&&(a=editorObjects[Editor.currentFloorTag][Editor.hoveredWall].coords,editorCtx.beginPath(),editorCtx.moveTo.apply(editorCtx,$jscomp.arrayFromIterable(coordToPx(a[0]))),editorCtx.lineTo.apply(editorCtx,$jscomp.arrayFromIterable(coordToPx(a[1]))),
editorCtx.lineCap="round",editorCtx.lineWidth=10,editorCtx.strokeStyle="#f44",editorCtx.stroke()))}function highlightLine(a,c,d,e,f,h){var k=new Vector(c,d);k=(new Vector(e,f)).sub(k).unit.angle2;a.beginPath();a.arc(c,d,h,k+Math.PI/2,k-Math.PI/2,!1);a.arc(e,f,h,k-Math.PI/2,k+Math.PI/2,!1);a.closePath()}
function resetEditorView(){var a=Math.max.apply(Math,$jscomp.arrayFromIterable(Building.boundaryXY[1].sub(Building.boundaryXY[0]))),c=Vector.midPoint.apply(Vector,$jscomp.arrayFromIterable(Building.boundaryXY));Editor.zoom=1.2*a;Editor.center=c;updateEditorViewport()}function updateEditorViewport(){var a=new Vector(Editor.zoom/2,Editor.zoom/2);Editor.boundary=[Editor.center.sub(a).sub(1),Editor.center.add(a).add(1)];renderEditorViewport()};var viewerPanel=document.getElementById("viewerPanel"),viewerCanvas=viewerPanel.querySelector("* canvas"),viewerCanvasWrapper=viewerPanel.querySelector(".canvasWrapper"),Viewer={renderer:new THREE.WebGLRenderer({canvas:viewerCanvas,alpha:!0,antialias:!0,preserveDrawingBuffer:!0}),scene:new THREE.Scene,camera:new THREE.PerspectiveCamera(fov=30,aspect=1,near=.1,far=1E3),lightDirect:new THREE.DirectionalLight(15658734,.6),lightDirectTarget:new THREE.Object3D,lightAmbient:new THREE.AmbientLight(8947848),
lightShadow:new THREE.DirectionalLight(15658734,0),lightShadowTarget:new THREE.Object3D,shadowOffset:new Vector(45,90),camStepped:!1,MAXZOOM:950,state:0,globalOffsetPosDiff:new Vector(0,0),mouseStartPos:new Vector(0,0),camMoving:!1,raycaster:new THREE.Raycaster,pointer:new THREE.Vector2};Viewer.renderer.setClearColor(16777215,0);Viewer.renderer.setSize(viewerResolution,viewerResolution);viewerCanvas.style.width="";viewerCanvas.style.height="";Viewer.scene.background=null;
Viewer.camera.up=new THREE.Vector3(0,0,1);Viewer.lightShadow.shadow.mapSize.width=1024;Viewer.lightShadow.shadow.mapSize.height=1024;Viewer.raycaster.layers.set(1);function updateViewerOffset(){Viewer.globalOffsetPosDiff.x=parseInt(viewerCanvas.getBoundingClientRect().x+document.documentElement.scrollLeft);Viewer.globalOffsetPosDiff.y=parseInt(viewerCanvas.getBoundingClientRect().y+document.documentElement.scrollTop)}viewerCanvas.onload=updateViewerOffset;
function polarCoord(a,c){a=Math.radians(a);c=Math.radians(-c-90);return new THREE.Vector3(Math.cos(a)*Math.cos(c),Math.cos(a)*Math.sin(c),Math.sin(a))}
function updateCamera(){Viewer.camera.alt=clamp(Viewer.camera.alt,-90,90);Viewer.camera.radius=clamp(Viewer.camera.radius,1,Viewer.MAXZOOM);Viewer.camera.azm%=360;var a=Viewer.camera.azm;Viewer.camStepped&&(a=45*Math.round(Viewer.camera.azm/45));Viewer.camera.position.copy(polarCoord(Viewer.camera.alt,a).multiplyScalar(Viewer.camera.radius).add(Viewer.camera.base));Viewer.camera.lookAt(Viewer.camera.base);90==Math.abs(Viewer.camera.alt)&&(Viewer.camera.rotation.z=Math.radians(-Math.sign(Viewer.camera.alt)*
a));Viewer.lightDirect.position.copy(polarCoord(Viewer.camera.alt,a+45).add(Viewer.camera.base));Viewer.lightDirectTarget.position.copy(Viewer.camera.base);Viewer.lightShadow.position.copy(polarCoord(Viewer.shadowOffset[0],a+Viewer.shadowOffset[1]).multiplyScalar(Viewer.camera.radius).add(Viewer.camera.base));Viewer.lightShadowTarget.position.copy(Viewer.camera.base);Viewer.renderer.render(Viewer.scene,Viewer.camera)}
function resetCamera(){Viewer.camera.base=new THREE.Vector3(0,0,0);Viewer.camera.alt=20;Viewer.camera.azm=-30;Viewer.camera.radius=50;updateCamera()}resetCamera();
function resetScene(){Viewer.scene.remove.apply(Viewer.scene,Viewer.scene.children);Viewer.scene.add(Viewer.lightDirect);Viewer.scene.add(Viewer.lightDirectTarget);Viewer.lightDirect.target=Viewer.lightDirectTarget;Viewer.scene.add(Viewer.lightAmbient);Viewer.scene.add(Viewer.lightShadow);Viewer.scene.add(Viewer.lightShadowTarget);Viewer.lightShadow.target=Viewer.lightShadowTarget}resetScene();
function mouseMoveViewerEvent(a){a=new Vector(a.pageX,a.pageY);var c=a.sub(Viewer.mouseStartPos);if(1==Viewer.state)Viewer.camera.azm+=c.x/canvasSizes[1]*180,Viewer.camera.alt+=c.y/canvasSizes[1]*180,0<c.size&&(Viewer.camMoving=!0);else if(2==Viewer.state){var d=Math.radians(-Viewer.camera.azm-90-90);d=(new THREE.Vector3(Math.cos(d),Math.sin(d),0)).multiplyScalar(c.x/canvasSizes[1]*10);Viewer.camera.base.add(new THREE.Vector3(d.x,d.y,c.y/canvasSizes[1]*10*Math.cos(Math.radians(Viewer.camera.alt))))}updateCamera();
Viewer.mouseStartPos=a}viewerCanvas.addEventListener("mousedown",function(a){0==Viewer.state&&(Viewer.mouseStartPos=new Vector(a.pageX,a.pageY),0==a.button?Viewer.state=1:1==a.button&&(Viewer.state=2),document.addEventListener("mousemove",mouseMoveViewerEvent))});viewerCanvas.addEventListener("wheel",function(a){a.preventDefault();Viewer.camera.radius-=a.wheelDeltaY/100*clamp(Math.pow(Viewer.camera.radius/50,1.2),1,Infinity);updateCamera()});
function selectViewerObject(a){1!=Building.workingPanelIdx||0!=a.button||Viewer.camMoving||(a=(new Vector(a.pageX,a.pageY)).sub(Viewer.globalOffsetPosDiff).div(canvasSizes[1]),a.x=clamp(a.x,0,1),a.y=clamp(a.y,0,1),a=a.mul(2).sub(1),a.y*=-1,Viewer.pointer.x=a.x,Viewer.pointer.y=a.y,Viewer.raycaster.setFromCamera(Viewer.pointer,Viewer.camera),a=Viewer.raycaster.intersectObjects(Viewer.scene.children),0==a.length?Editor.selectedWall="":(a=a[0].object.name,Editor.currentFloor=objectNameToFloorMap[a],
Editor.selectedWall=a))}viewerCanvas.addEventListener("mouseup",selectViewerObject);
var EDGEMATERIAL=new THREE.LineBasicMaterial({color:0,linewidth:1}),axisLength=10,axisXObjTemplate=new THREE.Line((new THREE.BufferGeometry).setFromPoints([new THREE.Vector3(0,0,0),new THREE.Vector3(axisLength,0,0)]),new THREE.LineBasicMaterial({color:16711680})),axisYObjTemplate=new THREE.Line((new THREE.BufferGeometry).setFromPoints([new THREE.Vector3(0,0,0),new THREE.Vector3(0,axisLength,0)]),new THREE.LineBasicMaterial({color:65280})),axisZObjTemplate=new THREE.Line((new THREE.BufferGeometry).setFromPoints([new THREE.Vector3(0,
0,0),new THREE.Vector3(0,0,axisLength)]),new THREE.LineBasicMaterial({color:255})),axisTrueNorthObjTemplate=new THREE.Line((new THREE.BufferGeometry).setFromPoints([new THREE.Vector3(0,0,0),new THREE.Vector3(0,axisLength,0)]),new THREE.LineDashedMaterial({color:65280,linewidth:2,dashSize:1.5,gapSize:1}));axisTrueNorthObjTemplate.computeLineDistances();var shadowCatcherMat=new THREE.ShadowMaterial;shadowCatcherMat.opacity=.5;
var matGhost=new THREE.MeshBasicMaterial({color:0,side:THREE.DoubleSide,transparent:!0,blending:THREE.AdditiveBlending});
function resetViewerView(){var a=[[].concat($jscomp.arrayFromIterable(Building.boundaryXY[0]),[Building.boundaryZ[0]]),[].concat($jscomp.arrayFromIterable(Building.boundaryXY[1]),[Building.boundaryZ[1]])],c=[],d=0;for(axis=0;3>axis;axis++)c.push((a[0][axis]+a[1][axis])/2),d+=Math.pow(a[1][axis]-a[0][axis],2);bldgRadius=Math.sqrt(d);Viewer.camera.base=new THREE.Vector3(c[0],c[1],c[2]);Viewer.camera.radius=2.5*bldgRadius;updateCamera()}
function addSurfaceObjectToViewer(a,c){c=void 0===c?!1:c;Viewer.scene.add(a.object);Viewer.scene.add(a.edgeObject);a=$jscomp.makeIterator(Object.entries(a.windows));for(var d=a.next();!d.done;d=a.next())d=$jscomp.makeIterator(d.value),d.next(),d=d.next().value,Viewer.scene.add(d.object),Viewer.scene.add(d.edgeObject);c||updateCamera()}
function removeSurfaceObjectFromViewer(a,c){c=void 0===c?!1:c;Viewer.scene.remove(a.object);Viewer.scene.remove(a.edgeObject);a=$jscomp.makeIterator(Object.entries(a.windows));for(var d=a.next();!d.done;d=a.next())d=$jscomp.makeIterator(d.value),d.next(),d=d.next().value,Viewer.scene.remove(d.object),Viewer.scene.remove(d.edgeObject);c||updateCamera()}
function refreshViewer(){resetScene();for(var a=$jscomp.makeIterator(Object.entries(viewerObjects)),c=a.next();!c.done;c=a.next()){c=$jscomp.makeIterator(c.value);c.next();c=c.next().value;c=$jscomp.makeIterator(Object.entries(c));for(var d=c.next();!d.done;d=c.next()){d=$jscomp.makeIterator(d.value);d.next();d=d.next().value;Viewer.scene.add(d.object);Viewer.scene.add(d.edgeObject);d=$jscomp.makeIterator(Object.entries(d.windows));for(var e=d.next();!e.done;e=d.next())e=$jscomp.makeIterator(e.value),
e.next(),e=e.next().value,Viewer.scene.add(e.object),Viewer.scene.add(e.edgeObject)}}updateCamera()};document.onmouseup=function(a){0==Building.workingPanelIdx?(1==a.button&&Editor.panning&&(Editor.panning=!1,document.removeEventListener("mousemove",mouseMoveEventPanning)),updateEditorViewport()):1==Building.workingPanelIdx&&(Viewer.state=0,Viewer.camMoving=!1,Viewer.camStepped&&(Viewer.camera.azm=45*Math.round(Viewer.camera.azm/45)),Viewer.camStepped=!1,document.removeEventListener("mousemove",mouseMoveViewerEvent))};
document.onkeydown=function(a){if(0==Building.workingPanelIdx)switch(a.key){case "Escape":if(0==Editor.state||1==Editor.state||2==Editor.state)Editor.state=-1,document.removeEventListener("mousemove",mouseMoveEventEditing),renderEditorViewport();break;case "Shift":Editor.angleSnap=!1,adjustMouseLeftEndPoint()}else if(1==Building.workingPanelIdx)switch(a.key){case "Shift":1==Viewer.state&&(Viewer.camStepped=!0,updateCamera())}"Delete"!=a.key&&"Backspace"!=a.key||""==Editor.selectedWall||"input"===
a.target.tagName.toLowerCase()||removeWallSegment(Editor.selectedWall)};document.onkeyup=function(a){if(0==Building.workingPanelIdx)switch(a.key){case "Shift":Editor.angleSnap=!0;adjustMouseLeftEndPoint();break;case "Enter":Editor.inputFieldVisibility&&addWall()}else if(1==Building.workingPanelIdx)switch(a.key){case "Shift":1==Viewer.state&&(Viewer.camStepped=!1,updateCamera())}};window.addEventListener("resize",function(a){updateDivider();updateEditorOffset()},!0);
window.addEventListener("load",function(){Editor.currentFloor=1;Editor.zoom=10;Editor.state=-1;Editor.hold=!1;updateEditorViewport();refreshViewer()});
window.addEventListener("load",function(){addWallSegment({floor:Editor.currentFloor,coords:[new Vector(0,0),new Vector(10,0)],texture:"rgb(150,150,150)"});addWallSegment({floor:Editor.currentFloor,coords:[new Vector(10,0),new Vector(10,5)],texture:"rgb(150,150,150)"});addWallSegment({floor:Editor.currentFloor,coords:[new Vector(10,5),new Vector(0,5)],texture:"rgb(150,150,150)"});addWallSegment({floor:Editor.currentFloor,coords:[new Vector(0,5),new Vector(0,0)],texture:"rgb(150,150,150)"});resetEditorView();
resetViewerView()});
